---
-  name :  Create a sudo user management
  user:
    name: "{{ manager_user }}"
    #password: "{{ password | password_hash('sha512') }}"
    #update_password: always
    generate_ssh_key: yes
    state: present

-  name :  Adding sudo privileges
  lineinfile: dest=/etc/sudoers state=present  line='{{ item }}' validate='visudo -cf %s'
  with_items:
    - "Cmnd_Alias RYPTOZEE = ALL, !/usr/bin/passwd root, !/usr/sbin/visudo, !/usr/bin/rm -rf /, !/usr/bin/rm -rf /*"
    - "%{{ manager_user }} ALL=(ALL) NOPASSWD: RYPTOZEE"

-  name :  Create a regular user
  user:
    name: "{{ item.user }}"
    password: "{{ item.pass | password_hash('sha512') }}"
    update_password: always
    groups: "{{ manager_user }}"
    state: present
  loop: "{{ userlist }}"

-  name :  configure the default configuration ansible.cfg
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg

-  name :  create the corresponding directory
  shell: "{{ item }}"
  with_items:
    - "mkdir -p /etc/ansible/keys"
    - "mkdir -p /etc/ansible/inventory"

-  name :  Mobile sudo user key to ansible directory
  copy:
    src: "/home/{{ manager_user }}/.ssh/id_rsa"
    dest: "/etc/ansible/keys/{{ manager_user }}_id_rsa"
    owner: adm
    group: adm
    mode: '0644'

-  name :  configure the default inventory
  template:
    src: default-hosts.ini.j2
    dest: /etc/ansible/inventory/default-hosts.ini